- huntflow_api_client/api.py
- huntflow_api_client/errors.py
- pyproject.toml
- tests/api.py
- tests/test_access_token.py
https://huntflow.atlassian.net/browse/INT-102 added InvalidRefreshTokenError and test for this error
> Int 102 additional exception

- .flake8
- huntflow_api_client/entities/webhooks.py
- huntflow_api_client/models/request/webhooks.py
- huntflow_api_client/models/response/webhooks.py
- huntflow_api_client/models/utils/common.py
- tests/test_webhooks.py
https://huntflow.atlassian.net/browse/INT-107
> [INT-107] Create Webhook entity

- huntflow_api_client/entities/dictionaries.py
- huntflow_api_client/entities/production_calendars.py
- huntflow_api_client/entities/tags.py
- huntflow_api_client/entities/webhooks.py
- huntflow_api_client/models/request/production_calendars.py
- huntflow_api_client/models/response/production_calendars.py
- tests/test_production_calendar.py
https://huntflow.atlassian.net/browse/INT-115
> [INT-115] Create calendar entity

- .github/workflows/python-linters.yml
- .github/workflows/python-tests.yml
https://huntflow.atlassian.net/browse/INT-128
> [INT-128] Update github actions versions.

- huntflow_api_client/models/common.py
- huntflow_api_client/models/request/applicants.py
- huntflow_api_client/models/request/dictionaries.py
- huntflow_api_client/models/request/divisions.py
- huntflow_api_client/models/request/tags.py
- huntflow_api_client/models/request/vacancies.py
- huntflow_api_client/models/request/vacancy_requests.py
- huntflow_api_client/models/request/webhooks.py
- huntflow_api_client/models/response/accounts.py
- huntflow_api_client/models/response/applicants.py
- huntflow_api_client/models/response/dictionaries.py
- huntflow_api_client/models/response/divisions.py
- huntflow_api_client/models/response/production_calendars.py
- huntflow_api_client/models/response/tags.py
- huntflow_api_client/models/response/vacancies.py
- huntflow_api_client/models/response/vacancy_requests.py
- huntflow_api_client/models/response/webhooks.py
Removed examples from Pydantic models
> [INT-123] Remove examples

- huntflow_api_client/entities/applicants.py
- huntflow_api_client/models/common.py
- huntflow_api_client/models/consts.py
- huntflow_api_client/models/request/applicants.py
- huntflow_api_client/models/response/applicants.py
- tests/test_entities/test_applicants.py
Added create worklog method for applicant entity
> [INT-122] create log method

- .pdm-python
- huntflow_api_client/entities/applicants.py
- huntflow_api_client/models/consts.py
- huntflow_api_client/models/response/applicants.py
- huntflow_api_client/models/response/offers.py
- huntflow_api_client/models/response/survey.py
- tests/test_entities/test_applicants.py
https://huntflow.atlassian.net/browse/INT-116
Added applicant's methods "search" "search_by_cursor" "list_log"
> [INT-116] additional applicant methods

- huntflow_api_client/entities/__init__.py
- huntflow_api_client/entities/delayed_tasks.py
- huntflow_api_client/models/consts.py
- huntflow_api_client/models/response/delayed_tasks.py
- pyproject.toml
- tests/test_entities/test_delayed_tasks.py
https://huntflow.atlassian.net/browse/INT-136
Added delayed task entity with get method
> [INT-136] Add delayed task entity

- huntflow_api_client/errors/errors.py
- pyproject.toml
https://huntflow.atlassian.net/browse/INT-138
Changed InvalidRefreshTokenError parent
> [INT-138] Change error inheritance

- huntflow_api_client/entities/applicants.py
- huntflow_api_client/entities/divisions.py
- tests/test_entities/test_applicants.py
https://huntflow.atlassian.net/browse/INT-142
Added a mutually exclusive restriction
> [INT-142] Add restriction to the Applicant.log_list method

- huntflow_api_client/models/consts.py
- huntflow_api_client/models/response/vacancy_requests.py
- pyproject.toml
https://huntflow.atlassian.net/browse/INT-143
Vacancy request statuses moved to consts
> [INT-143] Move vacancy request statuses

- huntflow_api_client/models/response/applicants.py
- pyproject.toml
- tests/test_entities/test_applicants.py
https://huntflow.atlassian.net/browse/INT-162
> [INT-162] Fix agreement field.

- huntflow_api_client/entities/applicants.py
- huntflow_api_client/entities/coworkers.py
- pyproject.toml
[INT-163](https://huntflow.atlassian.net/browse/INT-163)
> [INT-163] Fix handling of enum type params.

- huntflow_api_client/entities/__init__.py
- huntflow_api_client/entities/resume.py
- huntflow_api_client/models/consts.py
- huntflow_api_client/models/request/applicants.py
- huntflow_api_client/models/request/resume.py
- huntflow_api_client/models/response/applicants.py
- huntflow_api_client/models/response/resume.py
- pyproject.toml
- tests/test_entities/test_resume.py
https://huntflow.atlassian.net/browse/INT-173
> [INT-173] Add Resume entity.

- huntflow_api_client/entities/__init__.py
- huntflow_api_client/entities/users.py
- huntflow_api_client/models/common.py
- huntflow_api_client/models/response/users.py
- tests/test_entities/test_users.py
https://huntflow.atlassian.net/browse/INT-178
> [INT-178] - Add User entity.

- huntflow_api_client/entities/__init__.py
- huntflow_api_client/entities/email_templates.py
- huntflow_api_client/models/common.py
- huntflow_api_client/models/request/applicants.py
- huntflow_api_client/models/response/email_templates.py
- tests/test_entities/test_email_templates.py
https://huntflow.atlassian.net/browse/INT-177
> [INT-177] - Create MailTemplate entity.

- huntflow_api_client/models/response/applicant_logs.py
- pyproject.toml
https://huntflow.atlassian.net/browse/INT-185
Removed alias from field ApplicantLogItem.vacancy
> [INT-185] fix applicant log vacancy field

- huntflow_api_client/entities/coworkers.py
- huntflow_api_client/models/response/coworkers.py
- pyproject.toml
https://huntflow.atlassian.net/browse/INT-186
> [INT-86] use coworker member type enum

- huntflow_api_client/models/response/users.py
- pyproject.toml
https://huntflow.atlassian.net/browse/INT-189
> [INT-189] - Use MemberType in UserResponse model.

- huntflow_api_client/entities/applicant_logs.py
- huntflow_api_client/entities/applicant_on_vacancy.py
- pyproject.toml
- tests/test_entities/test_account_divisions.py
- tests/test_entities/test_applicant_logs.py
- tests/test_entities/test_applicant_on_vacancy.py
https://huntflow.atlassian.net/browse/INT-194
removed value errors
> [INT-194]Remove redundant value errors

- huntflow_api_client/entities/__init__.py
- huntflow_api_client/entities/user_settings.py
- huntflow_api_client/models/response/user_settings.py
- tests/test_entities/test_user_settings.py
https://huntflow.atlassian.net/browse/INT-215
> [INT-215] - Create UserSettings entity.

- huntflow_api_client/entities/vacancies.py
- huntflow_api_client/models/request/vacancies.py
- huntflow_api_client/models/response/vacancies.py
- tests/test_entities/test_vacancies.py
https://huntflow.atlassian.net/browse/INT-216
> [INT-216] - Extend Vacancy entity.

- huntflow_api_client/entities/__init__.py
- huntflow_api_client/entities/file.py
- huntflow_api_client/models/request/file.py
- huntflow_api_client/models/response/file.py
- tests/test_entities/test_file.py
https://huntflow.atlassian.net/browse/INT-219
> [INT-219] Create File entity with test.

- huntflow_api_client/entities/__init__.py
- huntflow_api_client/entities/multi_vacancies.py
- huntflow_api_client/models/request/multi_vacancies.py
- huntflow_api_client/models/response/muilti_vacancies.py
- tests/test_entities/test_multi_vacancies.py
https://huntflow.atlassian.net/browse/INT-225
> [INT-225] - Create MultiVacancy entity.

- huntflow_api_client/entities/__init__.py
- huntflow_api_client/entities/regions.py
- huntflow_api_client/models/response/regions.py
- tests/test_entities/test_regions.py
https://huntflow.atlassian.net/browse/INT-232
> [INT-232] - Add Region entity.

- huntflow_api_client/models/consts.py
https://huntflow.atlassian.net/browse/INT-266
> [INT-266] - extend AgreementState enum

- huntflow_api_client/entities/resume.py
- tests/test_entities/test_resume.py
https://huntflow.atlassian.net/browse/INT-290
> [INT-290] - Extend Resume entity

- huntflow_api_client/entities/__init__.py
- huntflow_api_client/entities/users_management.py
- huntflow_api_client/models/common.py
- huntflow_api_client/models/consts.py
- huntflow_api_client/models/request/users_management.py
- huntflow_api_client/models/response/users_management.py
- tests/test_entities/test_users_management.py
https://huntflow.atlassian.net/browse/INT-308
> [INT-308] - Create UsersManagement entity.

- huntflow_api_client/models/common.py
- huntflow_api_client/models/request/applicant_logs.py
- huntflow_api_client/models/request/file.py
- huntflow_api_client/models/request/multi_vacancies.py
- huntflow_api_client/models/request/vacancies.py
- huntflow_api_client/models/request/vacancy_requests.py
- huntflow_api_client/models/response/account_vacancy_request.py
- huntflow_api_client/models/response/applicant_logs.py
- huntflow_api_client/models/response/applicant_on_vacancy.py
- huntflow_api_client/models/response/applicants.py
- huntflow_api_client/models/response/coworkers.py
- huntflow_api_client/models/response/questionary.py
- huntflow_api_client/models/response/resume.py
- huntflow_api_client/models/response/users.py
- huntflow_api_client/models/response/vacancies.py
- pyproject.toml
https://huntflow.atlassian.net/browse/INT-321
> [INT-321] Fix errors

- huntflow_api_client/entities/users_management.py
- pyproject.toml
- tests/test_entities/test_users_management.py
https://huntflow.atlassian.net/browse/INT-403
> [INT-403] - Fix UsersManagement.delete_user().

- pyproject.toml
https://huntflow.atlassian.net/browse/INT-404
> [INT-404] - Update version.

- .github/scripts/autorelease.py
- .github/workflows/autorelease.yml
- autorelease.py
- pdm.lock
- pyproject.toml
https://huntflow.atlassian.net/browse/INT-450
Added autorelease python script and github action
> [INT-450] Add autorelease

- .github/workflows/autorelease.yml
- pdm.lock
- pyproject.toml
- tests/fixtures/tokens.py
https://huntflow.atlassian.net/browse/INT-450
> [INT-450] Add dependency packaging

- pyproject.toml
https://huntflow.atlassian.net/browse/INT-436
> [INT-436] - Release v2.0.0.

- huntflow_api_client/models/response/delayed_tasks.py
- pyproject.toml
- tests/test_entities/test_delayed_tasks.py
https://huntflow.atlassian.net/browse/INT-430
> [INT-430] - Fix DelayedTaskResponse model

- huntflow_api_client/entities/__init__.py
- huntflow_api_client/entities/applicant_reponse.py
- huntflow_api_client/models/response/applicant_response.py
- pdm.lock
- pyproject.toml
- tests/test_entities/test_applicant_response.py
**Task:**
https://huntflow.atlassian.net/browse/INT-561
**Done:**
Implement ApplicantResponse entity.
> [INT-561] - Create ApplicantResponse entity.
